2020-06-26T17:22:47|CRITICAL|root|Unhandled exception:Traceback (most recent call last):
  File "KeithleyApp.py", line 24, in <module>
    app = KeithleyTestApp(sys.argv)
  File "C:\Users\GingerLab\.julia\conda\3\envs\scopefoundry\lib\site-packages\ScopeFoundry\base_app.py", line 332, in __init__
    self.setup()
  File "KeithleyApp.py", line 9, in setup
    from keithley_sourcemeter.keithley_sourcemeter_hc import KeithleySourceMeterComponent
ModuleNotFoundError: No module named 'keithley_sourcemeter.keithley_sourcemeter_hc'

